version: '3'

services:
  mysql:
    image: 'mysql:latest'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 9911:3306
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"

  etcd:
    image: bitnami/etcd:3.5
    container_name: etcd
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - ./etcd/data:/bitnami/etcd-data
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379

  rabbitmq:
    image: rabbitmq:3-management # 使用 RabbitMQ 3.x 镜像
    container_name: rabbitmq  # 容器名称
    hostname: my-rabbit  # 容器主机名
    ports:
      - "5672:5672"  # RabbitMQ 默认端口
      - "15672:15672"  # RabbitMQ 管理界面端口
    restart: always  # 容器意外停止时自动重启

  redis:  # 服务名称
    image: "redis:latest"  # Redis镜像，使用最新版本
    container_name: redis  # 容器名称
    ports:
      - "6379:6379"  # 映射主机端口到容器端口
    volumes:
      - ./data:/data  # 挂载本地目录到容器内作为数据存储
    environment:
      - REDIS_PASSWORD=eshop  # 设置环境变量，例如Redis密码
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]  # 启动命令，设置Redis需要密码认证
    restart: always  # 总是重启容器，确保服务可用
