CREATE TABLE orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
    order_id VARCHAR(36) NOT NULL COMMENT '订单ID',
    user_id INT UNSIGNED NOT NULL COMMENT '用户ID',
    user_currency VARCHAR(10) NOT NULL COMMENT '用户使用的货币类型',
    stress_address VARCHAR(255) NOT NULL COMMENT '街道地址',
    city VARCHAR(100) NOT NULL COMMENT '城市',
    state VARCHAR(100) NOT NULL COMMENT '州/省份',
    country VARCHAR(100) NOT NULL COMMENT '国家',
    zip_code INT NOT NULL COMMENT '邮政编码',
    email VARCHAR(255) NOT NULL COMMENT '用户邮箱',
    created_at BIGINT NOT NULL COMMENT '订单创建时间（时间戳）',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间',
    UNIQUE KEY uk_order_id (order_id) -- 确保 order_id 唯一
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单表';

CREATE TABLE order_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
    order_id VARCHAR(36) NOT NULL COMMENT '订单ID',
    item_id INT UNSIGNED NOT NULL COMMENT '商品ID',
    item_name VARCHAR(255) NOT NULL COMMENT '商品名称',
    item_quantity INT UNSIGNED NOT NULL COMMENT '商品数量',
    item_cost FLOAT(8, 2) NOT NULL COMMENT '商品价格',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间',
    FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE -- 外键约束
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单项表';